#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define MAX_HEIGHT 400
#define MAX_WIDTH 300
#define RADIUS MAX_WIDTH/50
#define BRICK_WIDTH MAX_WIDTH/30
#define NO_COL_BRICK 7
#define NO_ROW_BRICK 3
#define PADDLE_SPEED 20

#endif // CONFIG_H_INCLUDED
