/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetLocalInfo */

#ifndef _Included_GetLocalInfo
#define _Included_GetLocalInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetLocalInfo
 * Method:    getLocalTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GetLocalInfo_getLocalTime
  (JNIEnv *, jobject);

/*
 * Class:     GetLocalInfo
 * Method:    getLocalOS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GetLocalInfo_getLocalOS
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
